version: '2'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - "25:25"
      - "80:80"
  riemann:
    build: .
    ports:
      - "4567:4567"
      - "5555:5555/tcp"
      - "5555:5555/udp"
      - "5556:5556"
    links:
      - maildev
